
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 30 2023 13:12:48 IST (Nov 30 2023 07:42:48 UTC)

// Verification Directory fv/fifo 

module fifo(w_clk, r_clk, rst, w_en, r_en, data_in, full_flag,
     empty_flag, data_out);
  input w_clk, r_clk, rst, w_en, r_en;
  input [7:0] data_in;
  output full_flag, empty_flag;
  output [7:0] data_out;
  wire w_clk, r_clk, rst, w_en, r_en;
  wire [7:0] data_in;
  wire full_flag, empty_flag;
  wire [7:0] data_out;
  wire [2:0] r_ptr;
  wire [2:0] w_ptr;
  wire [7:0] \memo[4] ;
  wire [7:0] \memo[7] ;
  wire [7:0] \memo[2] ;
  wire [7:0] \memo[1] ;
  wire [7:0] \memo[0] ;
  wire [7:0] \memo[3] ;
  wire [7:0] \memo[6] ;
  wire [7:0] \memo[5] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_123, n_124;
  assign r_ptr[0] = 1'b0;
  assign w_ptr[0] = 1'b0;
  assign w_ptr[1] = 1'b0;
  assign w_ptr[2] = 1'b0;
  assign r_ptr[1] = 1'b0;
  assign r_ptr[2] = 1'b0;
  assign data_out[0] = 1'b0;
  assign data_out[1] = 1'b0;
  assign data_out[2] = 1'b0;
  assign data_out[3] = 1'b0;
  assign data_out[4] = 1'b0;
  assign data_out[5] = 1'b0;
  assign data_out[6] = 1'b0;
  assign data_out[7] = 1'b0;
  INVXL g1655(.A (n_120), .Y (empty_flag));
  INVXL g1654(.A (n_115), .Y (full_flag));
  OAI221XL g1876__8780(.A0 (n_123), .A1 (n_6), .B0 (n_109), .B1
       (r_ptr[2]), .C0 (n_110), .Y (n_115));
  AOI221XL g1877__4296(.A0 (r_ptr[1]), .A1 (n_106), .B0 (n_124), .B1
       (n_20), .C0 (n_105), .Y (n_110));
  INVX4 g1878(.A (n_109), .Y (n_123));
  INVX8 g1879(.A (n_108), .Y (n_116));
  ADDHX1 g1880__3772(.A (n_9), .B (n_18), .CO (n_108), .S (n_109));
  NAND2BXL g1881__1474(.AN (n_107), .B (n_105), .Y (n_120));
  OAI221XL g1882__4547(.A0 (r_ptr[2]), .A1 (n_18), .B0 (w_ptr[2]), .B1
       (n_6), .C0 (n_104), .Y (n_107));
  INVX4 g1883(.A (n_124), .Y (n_106));
  XNOR2X1 g1885__9682(.A (w_ptr[1]), .B (r_ptr[1]), .Y (n_104));
  XNOR2X1 g1886__2683(.A (w_ptr[0]), .B (r_ptr[0]), .Y (n_105));
  INVX4 g1887(.A (n_117), .Y (n_9));
  NAND2BXL g1890__1309(.AN (w_ptr[1]), .B (w_ptr[0]), .Y (n_118));
  NAND2BXL g1891__6877(.AN (w_ptr[0]), .B (w_ptr[1]), .Y (n_119));
  NAND2X8 g2__2900(.A (n_118), .B (n_119), .Y (n_124));
  NAND2X8 g1896__2391(.A (w_ptr[1]), .B (w_ptr[0]), .Y (n_117));
  DFFHQX4 \data_out_reg[2]147 (.CK (r_clk), .D (n_98), .Q
       (data_out[2]));
  DFFHQX4 \data_out_reg[1]146 (.CK (r_clk), .D (n_94), .Q
       (data_out[1]));
  DFFHQX4 \data_out_reg[0]145 (.CK (r_clk), .D (n_93), .Q
       (data_out[0]));
  DFFHQX4 \data_out_reg[6]151 (.CK (r_clk), .D (n_92), .Q
       (data_out[6]));
  DFFHQX4 \data_out_reg[4]149 (.CK (r_clk), .D (n_96), .Q
       (data_out[4]));
  DFFHQX4 \data_out_reg[3]148 (.CK (r_clk), .D (n_99), .Q
       (data_out[3]));
  DFFHQX4 \data_out_reg[7]152 (.CK (r_clk), .D (n_97), .Q
       (data_out[7]));
  DFFHQX4 \data_out_reg[5]150 (.CK (r_clk), .D (n_95), .Q
       (data_out[5]));
  NAND2BXL g3328__7675(.AN (n_85), .B (n_86), .Y (n_99));
  NAND2BXL g3329__7118(.AN (n_91), .B (n_87), .Y (n_98));
  NAND2BXL g3330__8757(.AN (n_88), .B (n_89), .Y (n_97));
  NAND2BXL g3331__1786(.AN (n_79), .B (n_84), .Y (n_96));
  NAND2BXL g3332__5953(.AN (n_78), .B (n_81), .Y (n_95));
  NAND2BXL g3333__5703(.AN (n_83), .B (n_80), .Y (n_94));
  NAND2BXL g3334__7114(.AN (n_90), .B (n_82), .Y (n_93));
  NAND2BXL g3335__5266(.AN (n_76), .B (n_77), .Y (n_92));
  OAI221XL g3336__2250(.A0 (n_50), .A1 (n_22), .B0 (n_37), .B1 (n_28),
       .C0 (n_74), .Y (n_91));
  OAI221XL g3337__6083(.A0 (n_50), .A1 (n_7), .B0 (n_37), .B1 (n_17),
       .C0 (n_73), .Y (n_90));
  AOI221XL g3338__2703(.A0 (\memo[4] [7]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [7]), .C0 (n_60), .Y (n_89));
  OAI221XL g3339__5795(.A0 (n_50), .A1 (n_23), .B0 (n_37), .B1 (n_14),
       .C0 (n_75), .Y (n_88));
  AOI221XL g3340__7344(.A0 (\memo[4] [2]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [2]), .C0 (n_63), .Y (n_87));
  AOI221XL g3341__1840(.A0 (\memo[4] [3]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [3]), .C0 (n_62), .Y (n_86));
  OAI221XL g3342__5019(.A0 (n_50), .A1 (n_26), .B0 (n_37), .B1 (n_15),
       .C0 (n_70), .Y (n_85));
  AOI221XL g3343__1857(.A0 (\memo[4] [4]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [4]), .C0 (n_61), .Y (n_84));
  OAI221XL g3344__9906(.A0 (n_46), .A1 (n_8), .B0 (n_37), .B1 (n_16),
       .C0 (n_72), .Y (n_83));
  AOI221XL g3345__8780(.A0 (\memo[4] [0]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [0]), .C0 (n_59), .Y (n_82));
  AOI221XL g3346__4296(.A0 (\memo[4] [5]), .A1 (n_65), .B0 (n_48), .B1
       (\memo[2] [5]), .C0 (n_64), .Y (n_81));
  AOI221XL g3347__3772(.A0 (\memo[4] [1]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [1]), .C0 (n_58), .Y (n_80));
  OAI221XL g3348__1474(.A0 (n_46), .A1 (n_25), .B0 (n_37), .B1 (n_13),
       .C0 (n_71), .Y (n_79));
  OAI221XL g3349__4547(.A0 (n_66), .A1 (n_12), .B0 (n_52), .B1 (n_11),
       .C0 (n_68), .Y (n_78));
  AOI221XL g3350__9682(.A0 (\memo[4] [6]), .A1 (n_65), .B0 (n_53), .B1
       (\memo[7] [6]), .C0 (n_57), .Y (n_77));
  OAI221XL g3351__2683(.A0 (n_50), .A1 (n_24), .B0 (n_37), .B1 (n_27),
       .C0 (n_69), .Y (n_76));
  AOI222XL g3352__1309(.A0 (n_48), .A1 (\memo[2] [7]), .B0 (n_49), .B1
       (\memo[1] [7]), .C0 (n_67), .C1 (\memo[0] [7]), .Y (n_75));
  AOI222XL g3353__6877(.A0 (n_49), .A1 (\memo[1] [2]), .B0 (n_54), .B1
       (\memo[3] [2]), .C0 (n_67), .C1 (\memo[0] [2]), .Y (n_74));
  AOI222XL g3354__2900(.A0 (n_48), .A1 (\memo[2] [0]), .B0 (n_49), .B1
       (\memo[1] [0]), .C0 (n_67), .C1 (\memo[0] [0]), .Y (n_73));
  AOI222XL g3355__2391(.A0 (n_49), .A1 (\memo[1] [1]), .B0 (n_54), .B1
       (\memo[3] [1]), .C0 (n_67), .C1 (\memo[0] [1]), .Y (n_72));
  AOI222XL g3356__7675(.A0 (n_49), .A1 (\memo[1] [4]), .B0 (n_54), .B1
       (\memo[3] [4]), .C0 (n_67), .C1 (\memo[0] [4]), .Y (n_71));
  AOI222XL g3357__7118(.A0 (n_48), .A1 (\memo[2] [3]), .B0 (n_54), .B1
       (\memo[3] [3]), .C0 (n_67), .C1 (\memo[0] [3]), .Y (n_70));
  AOI222XL g3358__8757(.A0 (n_48), .A1 (\memo[2] [6]), .B0 (n_54), .B1
       (\memo[3] [6]), .C0 (n_67), .C1 (\memo[0] [6]), .Y (n_69));
  EDFFHQX8 \memo_reg[4][0] (.CK (w_clk), .D (data_in[0]), .E (n_5), .Q
       (\memo[4] [0]));
  EDFFHQX8 \memo_reg[7][0] (.CK (w_clk), .D (data_in[0]), .E (n_56), .Q
       (\memo[7] [0]));
  EDFFHQX8 \memo_reg[7][1] (.CK (w_clk), .D (data_in[1]), .E (n_56), .Q
       (\memo[7] [1]));
  EDFFHQX8 \memo_reg[7][2] (.CK (w_clk), .D (data_in[2]), .E (n_56), .Q
       (\memo[7] [2]));
  EDFFHQX8 \memo_reg[7][3] (.CK (w_clk), .D (data_in[3]), .E (n_56), .Q
       (\memo[7] [3]));
  EDFFHQX8 \memo_reg[7][4] (.CK (w_clk), .D (data_in[4]), .E (n_56), .Q
       (\memo[7] [4]));
  EDFFHQX8 \memo_reg[7][6] (.CK (w_clk), .D (data_in[6]), .E (n_56), .Q
       (\memo[7] [6]));
  EDFFHQX8 \memo_reg[7][7] (.CK (w_clk), .D (data_in[7]), .E (n_56), .Q
       (\memo[7] [7]));
  SMDFFHQX8 \r_ptr_reg[2]163 (.CK (r_clk), .D0 (n_6), .D1 (r_ptr[2]),
       .S0 (n_39), .SE (n_36), .SI (r_ptr[2]), .Q (r_ptr[2]));
  EDFFHQX8 \memo_reg[0][0] (.CK (w_clk), .D (data_in[0]), .E (n_4), .Q
       (\memo[0] [0]));
  EDFFHQX8 \memo_reg[0][1] (.CK (w_clk), .D (data_in[1]), .E (n_4), .Q
       (\memo[0] [1]));
  EDFFHQX8 \memo_reg[0][2] (.CK (w_clk), .D (data_in[2]), .E (n_4), .Q
       (\memo[0] [2]));
  EDFFHQX8 \memo_reg[0][3] (.CK (w_clk), .D (data_in[3]), .E (n_4), .Q
       (\memo[0] [3]));
  EDFFHQX8 \memo_reg[0][4] (.CK (w_clk), .D (data_in[4]), .E (n_4), .Q
       (\memo[0] [4]));
  EDFFHQX8 \memo_reg[0][6] (.CK (w_clk), .D (data_in[6]), .E (n_4), .Q
       (\memo[0] [6]));
  EDFFHQX8 \memo_reg[0][7] (.CK (w_clk), .D (data_in[7]), .E (n_4), .Q
       (\memo[0] [7]));
  EDFFHQX8 \memo_reg[6][5] (.CK (w_clk), .D (data_in[5]), .E (n_0), .Q
       (\memo[6] [5]));
  AOI222XL g3380__1786(.A0 (n_49), .A1 (\memo[1] [5]), .B0 (n_54), .B1
       (\memo[3] [5]), .C0 (n_36), .C1 (data_out[5]), .Y (n_68));
  EDFFHQX8 \memo_reg[4][3] (.CK (w_clk), .D (data_in[3]), .E (n_5), .Q
       (\memo[4] [3]));
  EDFFHQX8 \memo_reg[4][4] (.CK (w_clk), .D (data_in[4]), .E (n_5), .Q
       (\memo[4] [4]));
  EDFFHQX8 \memo_reg[4][5] (.CK (w_clk), .D (data_in[5]), .E (n_5), .Q
       (\memo[4] [5]));
  EDFFHQX8 \memo_reg[4][6] (.CK (w_clk), .D (data_in[6]), .E (n_5), .Q
       (\memo[4] [6]));
  EDFFHQX8 \memo_reg[4][7] (.CK (w_clk), .D (data_in[7]), .E (n_5), .Q
       (\memo[4] [7]));
  EDFFHQX8 \memo_reg[5][0] (.CK (w_clk), .D (data_in[0]), .E (n_55), .Q
       (\memo[5] [0]));
  EDFFHQX8 \memo_reg[5][2] (.CK (w_clk), .D (data_in[2]), .E (n_55), .Q
       (\memo[5] [2]));
  EDFFHQX8 \memo_reg[5][3] (.CK (w_clk), .D (data_in[3]), .E (n_55), .Q
       (\memo[5] [3]));
  EDFFHQX8 \memo_reg[5][5] (.CK (w_clk), .D (data_in[5]), .E (n_55), .Q
       (\memo[5] [5]));
  EDFFHQX8 \memo_reg[5][6] (.CK (w_clk), .D (data_in[6]), .E (n_55), .Q
       (\memo[5] [6]));
  EDFFHQX8 \memo_reg[5][7] (.CK (w_clk), .D (data_in[7]), .E (n_55), .Q
       (\memo[5] [7]));
  EDFFHQX8 \memo_reg[6][1] (.CK (w_clk), .D (data_in[1]), .E (n_0), .Q
       (\memo[6] [1]));
  EDFFHQX8 \memo_reg[6][4] (.CK (w_clk), .D (data_in[4]), .E (n_0), .Q
       (\memo[6] [4]));
  EDFFHQX8 \memo_reg[4][1] (.CK (w_clk), .D (data_in[1]), .E (n_5), .Q
       (\memo[4] [1]));
  EDFFHQX8 \memo_reg[4][2] (.CK (w_clk), .D (data_in[2]), .E (n_5), .Q
       (\memo[4] [2]));
  INVX4 g3401(.A (n_67), .Y (n_66));
  SMDFFHQX8 \r_ptr_reg[1]162 (.CK (r_clk), .D0 (r_ptr[0]), .D1 (n_19),
       .S0 (r_ptr[1]), .SE (n_36), .SI (r_ptr[1]), .Q (r_ptr[1]));
  EDFFHQX8 \memo_reg[2][5] (.CK (w_clk), .D (data_in[5]), .E (n_2), .Q
       (\memo[2] [5]));
  EDFFHQX8 \memo_reg[1][0] (.CK (w_clk), .D (data_in[0]), .E (n_3), .Q
       (\memo[1] [0]));
  EDFFHQX8 \memo_reg[1][1] (.CK (w_clk), .D (data_in[1]), .E (n_3), .Q
       (\memo[1] [1]));
  EDFFHQX8 \memo_reg[1][2] (.CK (w_clk), .D (data_in[2]), .E (n_3), .Q
       (\memo[1] [2]));
  EDFFHQX8 \memo_reg[1][3] (.CK (w_clk), .D (data_in[3]), .E (n_3), .Q
       (\memo[1] [3]));
  EDFFHQX8 \memo_reg[1][4] (.CK (w_clk), .D (data_in[4]), .E (n_3), .Q
       (\memo[1] [4]));
  EDFFHQX8 \memo_reg[1][5] (.CK (w_clk), .D (data_in[5]), .E (n_3), .Q
       (\memo[1] [5]));
  EDFFHQX8 \memo_reg[1][6] (.CK (w_clk), .D (data_in[6]), .E (n_3), .Q
       (\memo[1] [6]));
  EDFFHQX8 \memo_reg[2][4] (.CK (w_clk), .D (data_in[4]), .E (n_2), .Q
       (\memo[2] [4]));
  EDFFHQX8 \memo_reg[1][7] (.CK (w_clk), .D (data_in[7]), .E (n_3), .Q
       (\memo[1] [7]));
  EDFFHQX8 \memo_reg[2][0] (.CK (w_clk), .D (data_in[0]), .E (n_2), .Q
       (\memo[2] [0]));
  EDFFHQX8 \memo_reg[2][1] (.CK (w_clk), .D (data_in[1]), .E (n_2), .Q
       (\memo[2] [1]));
  EDFFHQX8 \memo_reg[2][2] (.CK (w_clk), .D (data_in[2]), .E (n_2), .Q
       (\memo[2] [2]));
  EDFFHQX8 \memo_reg[2][3] (.CK (w_clk), .D (data_in[3]), .E (n_2), .Q
       (\memo[2] [3]));
  AND4X1 g3417__5953(.A (n_44), .B (n_20), .C (n_19), .D (n_29), .Y
       (n_67));
  AND4X1 g3418__5703(.A (n_45), .B (n_30), .C (n_20), .D (n_19), .Y
       (n_65));
  AO22X1 g3419__7114(.A0 (n_47), .A1 (\memo[5] [5]), .B0 (n_51), .B1
       (\memo[6] [5]), .Y (n_64));
  AO22X1 g3420__5266(.A0 (n_48), .A1 (\memo[2] [2]), .B0 (n_47), .B1
       (\memo[5] [2]), .Y (n_63));
  AO22X1 g3421__2250(.A0 (n_49), .A1 (\memo[1] [3]), .B0 (n_47), .B1
       (\memo[5] [3]), .Y (n_62));
  AO22X1 g3422__6083(.A0 (n_48), .A1 (\memo[2] [4]), .B0 (n_51), .B1
       (\memo[6] [4]), .Y (n_61));
  AO22X1 g3423__2703(.A0 (n_47), .A1 (\memo[5] [7]), .B0 (n_54), .B1
       (\memo[3] [7]), .Y (n_60));
  AO22X1 g3424__5795(.A0 (n_47), .A1 (\memo[5] [0]), .B0 (n_54), .B1
       (\memo[3] [0]), .Y (n_59));
  AO22X1 g3425__7344(.A0 (n_48), .A1 (\memo[2] [1]), .B0 (n_51), .B1
       (\memo[6] [1]), .Y (n_58));
  AO22X1 g3426__1840(.A0 (n_49), .A1 (\memo[1] [6]), .B0 (n_47), .B1
       (\memo[5] [6]), .Y (n_57));
  EDFFHQX8 \memo_reg[3][6] (.CK (w_clk), .D (data_in[6]), .E (n_1), .Q
       (\memo[3] [6]));
  EDFFHQX8 \memo_reg[2][6] (.CK (w_clk), .D (data_in[6]), .E (n_2), .Q
       (\memo[2] [6]));
  EDFFHQX8 \memo_reg[3][7] (.CK (w_clk), .D (data_in[7]), .E (n_1), .Q
       (\memo[3] [7]));
  EDFFHQX8 \memo_reg[2][7] (.CK (w_clk), .D (data_in[7]), .E (n_2), .Q
       (\memo[2] [7]));
  EDFFHQX8 \memo_reg[3][0] (.CK (w_clk), .D (data_in[0]), .E (n_1), .Q
       (\memo[3] [0]));
  EDFFHQX8 \memo_reg[3][1] (.CK (w_clk), .D (data_in[1]), .E (n_1), .Q
       (\memo[3] [1]));
  EDFFHQX8 \memo_reg[3][2] (.CK (w_clk), .D (data_in[2]), .E (n_1), .Q
       (\memo[3] [2]));
  EDFFHQX8 \memo_reg[3][3] (.CK (w_clk), .D (data_in[3]), .E (n_1), .Q
       (\memo[3] [3]));
  EDFFHQX8 \memo_reg[3][4] (.CK (w_clk), .D (data_in[4]), .E (n_1), .Q
       (\memo[3] [4]));
  EDFFHQX8 \memo_reg[3][5] (.CK (w_clk), .D (data_in[5]), .E (n_1), .Q
       (\memo[3] [5]));
  EDFFHQX8 \r_ptr_reg[0]161 (.CK (r_clk), .D (n_19), .E (n_37), .Q
       (r_ptr[0]));
  EDFFHQX8 \w_ptr_reg[0]138 (.CK (w_clk), .D (n_10), .E (n_38), .Q
       (w_ptr[0]));
  EDFFHQX8 \w_ptr_reg[1]139 (.CK (w_clk), .D (n_124), .E (n_38), .Q
       (w_ptr[1]));
  EDFFHQX8 \w_ptr_reg[2]140 (.CK (w_clk), .D (n_123), .E (n_38), .Q
       (w_ptr[2]));
  AND2X1 g3442__5019(.A (n_43), .B (n_9), .Y (n_56));
  AND2X1 g3445__1857(.A (n_43), .B (n_21), .Y (n_55));
  INVX4 g3446(.A (n_53), .Y (n_52));
  INVX2 g3447(.A (n_50), .Y (n_51));
  INVX4 g3448(.A (n_47), .Y (n_46));
  AND3X1 g3449__9906(.A (n_40), .B (n_116), .C (n_29), .Y (n_54));
  AOI211XL g3450__8780(.A0 (n_9), .A1 (w_ptr[2]), .B0 (n_39), .C0
       (n_31), .Y (n_53));
  OAI211XL g3451__4296(.A0 (n_119), .A1 (n_18), .B0 (n_41), .C0 (n_30),
       .Y (n_50));
  AND3X1 g3452__3772(.A (n_35), .B (n_33), .C (n_29), .Y (n_49));
  AND3X1 g3453__1474(.A (n_34), .B (n_41), .C (n_29), .Y (n_48));
  AOI211XL g3454__4547(.A0 (n_21), .A1 (w_ptr[2]), .B0 (n_32), .C0
       (n_31), .Y (n_47));
  NAND2BXL g3457__9682(.AN (n_42), .B (w_ptr[2]), .Y (n_45));
  NAND2BXL g3458__2683(.AN (n_42), .B (n_18), .Y (n_44));
  AND2X1 g3460__1309(.A (w_ptr[2]), .B (n_38), .Y (n_43));
  INVX4 g3463(.A (n_39), .Y (n_40));
  INVX8 g3464(.A (n_37), .Y (n_36));
  NAND2BXL g3465__6877(.AN (w_ptr[1]), .B (n_10), .Y (n_42));
  AND2X1 g3466__2900(.A (n_19), .B (r_ptr[1]), .Y (n_41));
  NAND2BXL g3467__2391(.AN (n_20), .B (r_ptr[0]), .Y (n_39));
  AND2X2 g3468__7675(.A (n_115), .B (w_en), .Y (n_38));
  AND2X1 g3469__7118(.A (n_120), .B (r_en), .Y (n_37));
  INVX4 g3472(.A (n_32), .Y (n_33));
  INVX4 g3473(.A (n_31), .Y (n_30));
  NAND2BXL g3474__8757(.AN (n_118), .B (n_18), .Y (n_35));
  NAND2BXL g3475__1786(.AN (n_119), .B (n_18), .Y (n_34));
  NAND2BXL g3476__5953(.AN (r_ptr[1]), .B (r_ptr[0]), .Y (n_32));
  NAND2BXL g3477__5703(.AN (n_6), .B (r_en), .Y (n_31));
  AND2X1 g3478__7114(.A (n_6), .B (r_en), .Y (n_29));
  INVX4 g3479(.A (data_out[2]), .Y (n_28));
  INVX4 g3480(.A (data_out[6]), .Y (n_27));
  INVX4 g3487(.A (n_118), .Y (n_21));
  INVX8 g3489(.A (r_ptr[1]), .Y (n_20));
  INVX8 g3490(.A (r_ptr[0]), .Y (n_19));
  INVX8 g3491(.A (w_ptr[2]), .Y (n_18));
  INVX4 g3492(.A (data_out[0]), .Y (n_17));
  INVX4 g3493(.A (data_out[1]), .Y (n_16));
  INVX4 g3494(.A (data_out[3]), .Y (n_15));
  INVX4 g3495(.A (data_out[7]), .Y (n_14));
  INVX4 g3496(.A (data_out[4]), .Y (n_13));
  INVX4 g3499(.A (w_ptr[0]), .Y (n_10));
  INVX8 g3503(.A (r_ptr[2]), .Y (n_6));
  NOR2BX4 g1897__5266(.AN (n_38), .B (n_45), .Y (n_5));
  NOR2BX4 g3504__2250(.AN (n_38), .B (n_44), .Y (n_4));
  NOR2BX4 g3505__6083(.AN (n_38), .B (n_35), .Y (n_3));
  NOR2BX4 g3506__2703(.AN (n_38), .B (n_34), .Y (n_2));
  NOR2BX4 g3507__5795(.AN (n_38), .B (n_116), .Y (n_1));
  NOR2BX4 g3508__7344(.AN (n_43), .B (n_119), .Y (n_0));
  EDFFX2 \memo_reg[6][3] (.CK (w_clk), .D (data_in[3]), .E (n_0), .Q
       (\memo[6] [3]), .QN (n_26));
  EDFFX2 \memo_reg[5][4] (.CK (w_clk), .D (data_in[4]), .E (n_55), .Q
       (\memo[5] [4]), .QN (n_25));
  EDFFX2 \memo_reg[6][6] (.CK (w_clk), .D (data_in[6]), .E (n_0), .Q
       (\memo[6] [6]), .QN (n_24));
  EDFFX2 \memo_reg[6][7] (.CK (w_clk), .D (data_in[7]), .E (n_0), .Q
       (\memo[6] [7]), .QN (n_23));
  EDFFX2 \memo_reg[6][2] (.CK (w_clk), .D (data_in[2]), .E (n_0), .Q
       (\memo[6] [2]), .QN (n_22));
  EDFFX2 \memo_reg[0][5] (.CK (w_clk), .D (data_in[5]), .E (n_4), .Q
       (\memo[0] [5]), .QN (n_12));
  EDFFX2 \memo_reg[7][5] (.CK (w_clk), .D (data_in[5]), .E (n_56), .Q
       (\memo[7] [5]), .QN (n_11));
  EDFFX2 \memo_reg[5][1] (.CK (w_clk), .D (data_in[1]), .E (n_55), .Q
       (\memo[5] [1]), .QN (n_8));
  EDFFX2 \memo_reg[6][0] (.CK (w_clk), .D (data_in[0]), .E (n_0), .Q
       (\memo[6] [0]), .QN (n_7));
endmodule

