
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 30 2023 13:11:29 IST (Nov 30 2023 07:41:29 UTC)

// Verification Directory fv/fifo 

module fifo(w_clk, r_clk, rst, w_en, r_en, data_in, full_flag,
     empty_flag, data_out);
  input w_clk, r_clk, rst, w_en, r_en;
  input [7:0] data_in;
  output full_flag, empty_flag;
  output [7:0] data_out;
  wire w_clk, r_clk, rst, w_en, r_en;
  wire [7:0] data_in;
  wire full_flag, empty_flag;
  wire [7:0] data_out;
  wire [2:0] r_ptr;
  wire [2:0] w_ptr;
  wire [7:0] \memo[0] ;
  wire [7:0] \memo[4] ;
  wire [7:0] \memo[1] ;
  wire [7:0] \memo[2] ;
  wire [7:0] \memo[3] ;
  wire [7:0] \memo[7] ;
  wire [7:0] \memo[6] ;
  wire [7:0] \memo[5] ;
  wire n_49, n_50, n_51, n_56, n_57, n_58, n_358, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_373, n_374;
  wire n_376, n_378, n_380, n_382, n_384, n_386, n_388, n_663;
  wire n_664, n_717, n_718, n_721, n_722, n_724, n_725, n_727;
  wire n_731, n_732, n_734, n_735, n_737, n_739, n_745, n_746;
  wire n_747, n_748, n_749, n_750, n_751, n_752, n_753, n_754;
  wire n_765, n_766, n_767, n_768, n_769, n_770, n_771, n_774;
  wire n_792, n_793, n_794, n_795, n_796, n_801, n_802, n_807;
  wire n_808, n_811, n_814, n_817, n_820, n_823, n_826, n_829;
  wire n_847, n_848, n_849, n_850, n_851, n_884, n_885, n_886;
  wire n_887, n_888, n_889, n_890, n_891, n_892, n_893, n_894;
  wire n_895, n_896, n_897, n_898, n_899, n_932, n_933, n_934;
  wire n_935, n_936, n_937, n_938, n_939, n_940, n_941, n_942;
  wire n_943, n_944, n_945, n_946, n_947, n_980, n_981, n_982;
  wire n_983, n_984, n_985, n_986, n_987, n_988, n_989, n_990;
  wire n_991, n_992, n_993, n_994, n_995, n_1028, n_1029, n_1030;
  wire n_1031, n_1032, n_1033, n_1034, n_1035, n_1036, n_1037, n_1038;
  wire n_1039, n_1040, n_1041, n_1042, n_1043, n_1076, n_1077, n_1078;
  wire n_1079, n_1080, n_1081, n_1082, n_1083, n_1084, n_1085, n_1086;
  wire n_1087, n_1088, n_1089, n_1090, n_1091, n_1124, n_1125, n_1126;
  wire n_1127, n_1128, n_1129, n_1130, n_1131, n_1132, n_1133, n_1134;
  wire n_1135, n_1136, n_1137, n_1138, n_1139, n_1172, n_1173, n_1174;
  wire n_1175, n_1176, n_1177, n_1178, n_1179, n_1180, n_1181, n_1182;
  wire n_1183, n_1184, n_1185, n_1186, n_1187, n_1220, n_1221, n_1222;
  wire n_1223, n_1224, n_1225, n_1226, n_1227, n_1228, n_1229, n_1230;
  wire n_1231, n_1232, n_1233, n_1234, n_1235, n_1278, n_1279, n_1280;
  wire n_1281, n_1282, n_1283, n_1284, n_1285;
  assign r_ptr[2] = 1'b0;
  assign w_ptr[2] = 1'b0;
  assign w_ptr[1] = 1'b0;
  assign w_ptr[0] = 1'b0;
  assign r_ptr[1] = 1'b0;
  assign r_ptr[0] = 1'b0;
  assign data_out[0] = 1'b0;
  assign data_out[1] = 1'b0;
  assign data_out[2] = 1'b0;
  assign data_out[3] = 1'b0;
  assign data_out[4] = 1'b0;
  assign data_out[5] = 1'b0;
  assign data_out[6] = 1'b0;
  assign data_out[7] = 1'b0;
  CDN_flop \data_out_reg[0]145 (.clk (r_clk), .d (n_374), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[0]));
  CDN_flop \data_out_reg[1]146 (.clk (r_clk), .d (n_376), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[1]));
  CDN_flop \data_out_reg[2]147 (.clk (r_clk), .d (n_378), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[2]));
  CDN_flop \data_out_reg[3]148 (.clk (r_clk), .d (n_380), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[3]));
  CDN_flop \data_out_reg[4]149 (.clk (r_clk), .d (n_382), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[4]));
  CDN_flop \data_out_reg[5]150 (.clk (r_clk), .d (n_384), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[5]));
  CDN_flop \data_out_reg[6]151 (.clk (r_clk), .d (n_386), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[6]));
  CDN_flop \data_out_reg[7]152 (.clk (r_clk), .d (n_388), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_out[7]));
  not g600 (n_663, n_373);
  nand g829 (n_732, r_ptr[0], r_ptr[1]);
  nand g859 (n_50, n_721, n_722);
  nand g1122 (n_373, r_en, n_718);
  not g1123 (empty_flag, n_718);
  not g1124 (full_flag, n_727);
  or g1125 (n_721, w_ptr[0], wc);
  not gc (wc, w_ptr[1]);
  or g1126 (n_722, wc0, w_ptr[1]);
  not gc0 (wc0, w_ptr[0]);
  not g1127 (n_49, w_ptr[0]);
  not g1128 (n_56, r_ptr[0]);
  or g1160 (n_767, w_ptr[2], n_722);
  or g1163 (n_768, w_ptr[2], n_721);
  or g1196 (n_718, n_792, n_793);
  or g1232 (n_727, n_847, n_848);
  or g1422 (n_382, n_1090, n_1091);
  or g1423 (n_380, n_1042, n_1043);
  or g1424 (n_384, n_1138, n_1139);
  or g1425 (n_376, n_946, n_947);
  or g1428 (n_378, n_994, n_995);
  or g1429 (n_386, n_1186, n_1187);
  or g1430 (n_374, n_898, n_899);
  or g1431 (n_388, n_1234, n_1235);
  or g1438 (n_995, n_992, n_993);
  or g1439 (n_1091, n_1088, n_1089);
  or g1440 (n_1139, n_1136, n_1137);
  or g1441 (n_1235, n_1232, n_1233);
  or g1442 (n_899, n_896, n_897);
  or g1443 (n_1187, n_1184, n_1185);
  or g1450 (n_1043, n_1040, n_1041);
  or g1453 (n_765, wc1, n_731);
  not gc1 (wc1, w_ptr[2]);
  or g1454 (n_947, n_944, n_945);
  or g1455 (n_1089, wc2, n_1085);
  not gc2 (wc2, n_1084);
  or g1456 (n_993, wc3, n_989);
  not gc3 (wc3, n_988);
  or g1457 (n_1041, wc4, n_1037);
  not gc4 (wc4, n_1036);
  or g1458 (n_897, wc5, n_893);
  not gc5 (wc5, n_892);
  or g1459 (n_898, n_894, n_895);
  nand g1460 (n_731, n_727, w_en);
  not g1461 (n_664, n_731);
  or g1462 (n_1186, n_1182, n_1183);
  or g1463 (n_1185, wc6, n_1181);
  not gc6 (wc6, n_1180);
  or g1464 (n_1233, wc7, n_1229);
  not gc7 (wc7, n_1228);
  or g1465 (n_1137, wc8, n_1133);
  not gc8 (wc8, n_1132);
  or g1466 (n_1138, n_1134, n_1135);
  or g1467 (n_1234, n_1230, n_1231);
  or g1468 (n_945, wc9, n_941);
  not gc9 (wc9, n_940);
  or g1469 (n_946, n_942, n_943);
  or g1470 (n_1090, n_1086, n_1087);
  or g1471 (n_994, n_990, n_991);
  or g1472 (n_1042, n_1038, n_1039);
  nand g1473 (n_991, n_984, n_985);
  nand g1474 (n_989, n_980, n_981);
  nand g1475 (n_943, n_936, n_937);
  nand g1476 (n_1181, n_1172, n_1173);
  nand g1477 (n_941, n_932, n_933);
  nand g1478 (n_1037, n_1028, n_1029);
  nand g1479 (n_1135, n_1128, n_1129);
  nand g1480 (n_1039, n_1032, n_1033);
  nand g1481 (n_1133, n_1124, n_1125);
  nand g1482 (n_1183, n_1176, n_1177);
  nand g1483 (n_895, n_888, n_889);
  nand g1484 (n_893, n_884, n_885);
  nand g1485 (n_1085, n_1076, n_1077);
  nand g1486 (n_1087, n_1080, n_1081);
  nand g1487 (n_1229, n_1220, n_1221);
  nand g1488 (n_1231, n_1224, n_1225);
  nand g1489 (n_1124, n_373, data_out[5]);
  or g1490 (n_1125, n_749, wc10);
  not gc10 (wc10, \memo[0] [5]);
  nand g1491 (n_932, n_373, data_out[1]);
  nand g1492 (n_1088, n_1082, n_1083);
  or g1493 (n_985, n_746, wc11);
  not gc11 (wc11, \memo[4] [2]);
  nand g1494 (n_1086, n_1078, n_1079);
  nand g1495 (n_1182, n_1174, n_1175);
  nand g1496 (n_1184, n_1178, n_1179);
  nand g1497 (n_1220, n_373, data_out[7]);
  or g1498 (n_981, n_749, wc12);
  not gc12 (wc12, \memo[0] [2]);
  or g1499 (n_1081, n_746, wc13);
  not gc13 (wc13, \memo[4] [4]);
  nand g1500 (n_896, n_890, n_891);
  or g1501 (n_1221, n_749, wc14);
  not gc14 (wc14, \memo[0] [7]);
  or g1502 (n_1177, n_746, wc15);
  not gc15 (wc15, \memo[4] [6]);
  or g1503 (n_1077, n_749, wc16);
  not gc16 (wc16, \memo[0] [4]);
  nand g1504 (n_1076, n_373, data_out[4]);
  or g1505 (n_1129, n_746, wc17);
  not gc17 (wc17, \memo[4] [5]);
  nand g1506 (n_894, n_886, n_887);
  nand g1507 (n_944, n_938, n_939);
  nand g1508 (n_1040, n_1034, n_1035);
  or g1509 (n_885, n_749, wc18);
  not gc18 (wc18, \memo[0] [0]);
  nand g1510 (n_1038, n_1030, n_1031);
  nand g1511 (n_1134, n_1126, n_1127);
  nand g1512 (n_942, n_934, n_935);
  nand g1513 (n_884, n_373, data_out[0]);
  or g1514 (n_1225, n_746, wc19);
  not gc19 (wc19, \memo[4] [7]);
  or g1515 (n_1033, n_746, wc20);
  not gc20 (wc20, \memo[4] [3]);
  or g1516 (n_847, n_851, n_717);
  or g1517 (n_889, n_746, wc21);
  not gc21 (wc21, \memo[4] [0]);
  or g1518 (n_937, n_746, wc22);
  not gc22 (wc22, \memo[4] [1]);
  or g1519 (n_1029, n_749, wc23);
  not gc23 (wc23, \memo[0] [3]);
  nand g1520 (n_1028, n_373, data_out[3]);
  nand g1521 (n_1136, n_1130, n_1131);
  nand g1522 (n_1172, n_373, data_out[6]);
  or g1523 (n_1173, n_749, wc24);
  not gc24 (wc24, \memo[0] [6]);
  nand g1524 (n_992, n_986, n_987);
  nand g1525 (n_1232, n_1226, n_1227);
  nand g1526 (n_990, n_982, n_983);
  nand g1527 (n_1230, n_1222, n_1223);
  nand g1528 (n_980, n_373, data_out[2]);
  or g1529 (n_933, n_749, wc25);
  not gc25 (wc25, \memo[0] [1]);
  or g1530 (n_1126, n_751, wc26);
  not gc26 (wc26, \memo[1] [5]);
  or g1531 (n_1127, n_752, wc27);
  not gc27 (wc27, \memo[2] [5]);
  or g1532 (n_1128, n_748, wc28);
  not gc28 (wc28, \memo[3] [5]);
  or g1533 (n_1084, n_754, wc29);
  not gc29 (wc29, \memo[7] [4]);
  or g1534 (n_1083, n_753, wc30);
  not gc30 (wc30, \memo[6] [4]);
  or g1535 (n_1082, n_750, wc31);
  not gc31 (wc31, \memo[5] [4]);
  or g1536 (n_1080, n_748, wc32);
  not gc32 (wc32, \memo[3] [4]);
  or g1537 (n_1079, n_752, wc33);
  not gc33 (wc33, \memo[2] [4]);
  or g1538 (n_1078, n_751, wc34);
  not gc34 (wc34, \memo[1] [4]);
  or g1539 (n_1130, n_750, wc35);
  not gc35 (wc35, \memo[5] [5]);
  or g1540 (n_1131, n_753, wc36);
  not gc36 (wc36, \memo[6] [5]);
  or g1541 (n_1132, n_754, wc37);
  not gc37 (wc37, \memo[7] [5]);
  or g1542 (n_1036, n_754, wc38);
  not gc38 (wc38, \memo[7] [3]);
  or g1543 (n_1035, n_753, wc39);
  not gc39 (wc39, \memo[6] [3]);
  or g1544 (n_1034, n_750, wc40);
  not gc40 (wc40, \memo[5] [3]);
  or g1545 (n_1032, n_748, wc41);
  not gc41 (wc41, \memo[3] [3]);
  or g1546 (n_1031, n_752, wc42);
  not gc42 (wc42, \memo[2] [3]);
  or g1547 (n_1030, n_751, wc43);
  not gc43 (wc43, \memo[1] [3]);
  or g1548 (n_1174, n_751, wc44);
  not gc44 (wc44, \memo[1] [6]);
  or g1549 (n_1175, n_752, wc45);
  not gc45 (wc45, \memo[2] [6]);
  or g1550 (n_988, n_754, wc46);
  not gc46 (wc46, \memo[7] [2]);
  or g1551 (n_987, n_753, wc47);
  not gc47 (wc47, \memo[6] [2]);
  or g1552 (n_986, n_750, wc48);
  not gc48 (wc48, \memo[5] [2]);
  or g1553 (n_984, n_748, wc49);
  not gc49 (wc49, \memo[3] [2]);
  or g1554 (n_983, n_752, wc50);
  not gc50 (wc50, \memo[2] [2]);
  or g1555 (n_982, n_751, wc51);
  not gc51 (wc51, \memo[1] [2]);
  or g1556 (n_746, n_802, r_ptr[1]);
  or g1557 (n_1176, n_748, wc52);
  not gc52 (wc52, \memo[3] [6]);
  or g1558 (n_1178, n_750, wc53);
  not gc53 (wc53, \memo[5] [6]);
  or g1559 (n_1179, n_753, wc54);
  not gc54 (wc54, \memo[6] [6]);
  or g1560 (n_1180, n_754, wc55);
  not gc55 (wc55, \memo[7] [6]);
  or g1561 (n_940, n_754, wc56);
  not gc56 (wc56, \memo[7] [1]);
  or g1562 (n_939, n_753, wc57);
  not gc57 (wc57, \memo[6] [1]);
  or g1563 (n_938, n_750, wc58);
  not gc58 (wc58, \memo[5] [1]);
  or g1564 (n_936, n_748, wc59);
  not gc59 (wc59, \memo[3] [1]);
  or g1565 (n_935, n_752, wc60);
  not gc60 (wc60, \memo[2] [1]);
  or g1566 (n_1227, n_753, wc61);
  not gc61 (wc61, \memo[6] [7]);
  or g1567 (n_1222, n_751, wc62);
  not gc62 (wc62, \memo[1] [7]);
  or g1568 (n_892, n_754, wc63);
  not gc63 (wc63, \memo[7] [0]);
  or g1569 (n_891, n_753, wc64);
  not gc64 (wc64, \memo[6] [0]);
  or g1570 (n_890, n_750, wc65);
  not gc65 (wc65, \memo[5] [0]);
  or g1571 (n_888, n_748, wc66);
  not gc66 (wc66, \memo[3] [0]);
  or g1572 (n_887, n_752, wc67);
  not gc67 (wc67, \memo[2] [0]);
  or g1573 (n_886, n_751, wc68);
  not gc68 (wc68, \memo[1] [0]);
  or g1574 (n_1228, n_754, wc69);
  not gc69 (wc69, \memo[7] [7]);
  nand g1575 (n_851, n_849, n_850);
  or g1576 (n_1226, n_750, wc70);
  not gc70 (wc70, \memo[5] [7]);
  or g1577 (n_1223, n_752, wc71);
  not gc71 (wc71, \memo[2] [7]);
  or g1578 (n_1224, n_748, wc72);
  not gc72 (wc72, \memo[3] [7]);
  or g1579 (n_749, n_808, r_ptr[1]);
  or g1580 (n_934, n_751, wc73);
  not gc73 (wc73, \memo[1] [1]);
  or g1581 (n_850, wc74, r_ptr[2]);
  not gc74 (wc74, n_51);
  or g1582 (n_752, n_829, n_747);
  or g1583 (n_750, wc75, n_735);
  not gc75 (wc75, n_771);
  or g1584 (n_751, n_826, n_747);
  or g1585 (n_802, n_801, r_ptr[0]);
  or g1586 (n_748, n_823, n_747);
  or g1587 (n_753, wc76, n_734);
  not gc76 (wc76, n_770);
  or g1588 (n_808, n_807, r_ptr[0]);
  or g1589 (n_849, n_51, wc77);
  not gc77 (wc77, r_ptr[2]);
  or g1590 (n_754, wc78, n_732);
  not gc78 (wc78, n_769);
  or g1591 (n_792, n_796, wc79);
  not gc79 (wc79, n_717);
  or g1592 (n_829, wc80, n_734);
  not gc80 (wc80, n_768);
  or g1593 (n_826, wc81, n_735);
  not gc81 (wc81, n_767);
  or g1594 (n_823, wc82, n_732);
  not gc82 (wc82, n_725);
  or g1595 (n_807, wc83, n_747);
  not gc83 (wc83, n_739);
  nand g1596 (n_51, n_725, n_820);
  or g1597 (n_801, wc84, n_745);
  not gc84 (wc84, n_737);
  nand g1598 (n_771, n_766, n_817);
  nand g1599 (n_770, n_766, n_814);
  nand g1600 (n_769, n_766, n_811);
  or g1601 (n_1278, wc85, n_50);
  not gc85 (wc85, r_ptr[1]);
  or g1602 (n_1279, r_ptr[1], wc86);
  not gc86 (wc86, n_50);
  nand g1603 (n_848, n_1278, n_1279);
  or g1604 (n_739, n_774, w_ptr[2]);
  or g1605 (n_737, n_774, wc87);
  not gc87 (wc87, w_ptr[2]);
  or g1606 (n_814, wc88, n_745);
  not gc88 (wc88, n_721);
  nand g1607 (n_57, n_734, n_735);
  or g1608 (n_817, wc89, n_745);
  not gc89 (wc89, n_722);
  or g1609 (n_766, n_745, w_ptr[2]);
  nand g1610 (n_1280, n_732, r_ptr[2]);
  or g1611 (n_1281, n_732, r_ptr[2]);
  nand g1612 (n_58, n_1280, n_1281);
  nand g1613 (n_820, n_724, w_ptr[2]);
  or g1614 (n_725, n_724, w_ptr[2]);
  nand g1615 (n_796, n_794, n_795);
  or g1616 (n_811, wc90, n_745);
  not gc90 (wc90, n_724);
  or g1617 (n_774, w_ptr[1], w_ptr[0]);
  or g1618 (n_735, r_ptr[1], wc91);
  not gc91 (wc91, r_ptr[0]);
  or g1619 (n_734, wc92, r_ptr[0]);
  not gc92 (wc92, r_ptr[1]);
  or g1620 (n_794, w_ptr[1], wc93);
  not gc93 (wc93, r_ptr[1]);
  nand g1621 (n_1282, w_ptr[0], r_ptr[0]);
  or g1622 (n_1283, w_ptr[0], r_ptr[0]);
  nand g1623 (n_717, n_1282, n_1283);
  or g1624 (n_747, wc94, r_ptr[2]);
  not gc94 (wc94, r_en);
  nand g1625 (n_724, w_ptr[0], w_ptr[1]);
  or g1626 (n_1284, wc95, r_ptr[2]);
  not gc95 (wc95, w_ptr[2]);
  or g1627 (n_1285, w_ptr[2], wc96);
  not gc96 (wc96, r_ptr[2]);
  nand g1628 (n_793, n_1284, n_1285);
  or g1629 (n_795, wc97, r_ptr[1]);
  not gc97 (wc97, w_ptr[1]);
  nand g1630 (n_745, r_ptr[2], r_en);
  nor g1631 (n_362, n_725, n_731);
  nor g1632 (n_361, n_731, n_768);
  nor g1633 (n_360, n_731, n_767);
  nor g1634 (n_363, n_731, n_737);
  nor g1635 (n_358, n_731, n_739);
  nor g1636 (n_366, n_765, n_724);
  nor g1637 (n_365, n_721, n_765);
  nor g1638 (n_364, n_722, n_765);
  CDN_flop \memo_reg[0][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [0]));
  CDN_flop \memo_reg[0][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [1]));
  CDN_flop \memo_reg[0][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [2]));
  CDN_flop \memo_reg[0][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [3]));
  CDN_flop \memo_reg[0][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [4]));
  CDN_flop \memo_reg[0][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [5]));
  CDN_flop \memo_reg[0][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [6]));
  CDN_flop \memo_reg[0][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_358), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[0] [7]));
  CDN_flop \memo_reg[1][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [0]));
  CDN_flop \memo_reg[1][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [1]));
  CDN_flop \memo_reg[1][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [2]));
  CDN_flop \memo_reg[1][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [3]));
  CDN_flop \memo_reg[1][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [4]));
  CDN_flop \memo_reg[1][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [5]));
  CDN_flop \memo_reg[1][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [6]));
  CDN_flop \memo_reg[1][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[1] [7]));
  CDN_flop \memo_reg[2][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [0]));
  CDN_flop \memo_reg[2][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [1]));
  CDN_flop \memo_reg[2][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [2]));
  CDN_flop \memo_reg[2][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [3]));
  CDN_flop \memo_reg[2][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [4]));
  CDN_flop \memo_reg[2][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [5]));
  CDN_flop \memo_reg[2][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [6]));
  CDN_flop \memo_reg[2][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[2] [7]));
  CDN_flop \memo_reg[3][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [0]));
  CDN_flop \memo_reg[3][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [1]));
  CDN_flop \memo_reg[3][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [2]));
  CDN_flop \memo_reg[3][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [3]));
  CDN_flop \memo_reg[3][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [4]));
  CDN_flop \memo_reg[3][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [5]));
  CDN_flop \memo_reg[3][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [6]));
  CDN_flop \memo_reg[3][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[3] [7]));
  CDN_flop \memo_reg[4][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [0]));
  CDN_flop \memo_reg[4][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [1]));
  CDN_flop \memo_reg[4][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [2]));
  CDN_flop \memo_reg[4][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [3]));
  CDN_flop \memo_reg[4][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [4]));
  CDN_flop \memo_reg[4][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [5]));
  CDN_flop \memo_reg[4][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [6]));
  CDN_flop \memo_reg[4][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[4] [7]));
  CDN_flop \memo_reg[5][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [0]));
  CDN_flop \memo_reg[5][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [1]));
  CDN_flop \memo_reg[5][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [2]));
  CDN_flop \memo_reg[5][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [3]));
  CDN_flop \memo_reg[5][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [4]));
  CDN_flop \memo_reg[5][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [5]));
  CDN_flop \memo_reg[5][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [6]));
  CDN_flop \memo_reg[5][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[5] [7]));
  CDN_flop \memo_reg[6][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [0]));
  CDN_flop \memo_reg[6][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [1]));
  CDN_flop \memo_reg[6][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [2]));
  CDN_flop \memo_reg[6][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [3]));
  CDN_flop \memo_reg[6][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [4]));
  CDN_flop \memo_reg[6][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [5]));
  CDN_flop \memo_reg[6][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [6]));
  CDN_flop \memo_reg[6][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[6] [7]));
  CDN_flop \memo_reg[7][0] (.clk (w_clk), .d (data_in[0]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [0]));
  CDN_flop \memo_reg[7][1] (.clk (w_clk), .d (data_in[1]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [1]));
  CDN_flop \memo_reg[7][2] (.clk (w_clk), .d (data_in[2]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [2]));
  CDN_flop \memo_reg[7][3] (.clk (w_clk), .d (data_in[3]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [3]));
  CDN_flop \memo_reg[7][4] (.clk (w_clk), .d (data_in[4]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [4]));
  CDN_flop \memo_reg[7][5] (.clk (w_clk), .d (data_in[5]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [5]));
  CDN_flop \memo_reg[7][6] (.clk (w_clk), .d (data_in[6]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [6]));
  CDN_flop \memo_reg[7][7] (.clk (w_clk), .d (data_in[7]), .sena
       (n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (\memo[7] [7]));
  CDN_flop \r_ptr_reg[0]161 (.clk (r_clk), .d (n_56), .sena (n_663),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (r_ptr[0]));
  CDN_flop \r_ptr_reg[1]162 (.clk (r_clk), .d (n_57), .sena (n_663),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (r_ptr[1]));
  CDN_flop \r_ptr_reg[2]163 (.clk (r_clk), .d (n_58), .sena (n_663),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (r_ptr[2]));
  CDN_flop \w_ptr_reg[0]138 (.clk (w_clk), .d (n_49), .sena (n_664),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (w_ptr[0]));
  CDN_flop \w_ptr_reg[1]139 (.clk (w_clk), .d (n_50), .sena (n_664),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (w_ptr[1]));
  CDN_flop \w_ptr_reg[2]140 (.clk (w_clk), .d (n_51), .sena (n_664),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (w_ptr[2]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
